#!/bin/bash
# Copyright (C) Dmitry Igrishin

cefeika_libraries="algo assert base filesystem mem rajson wscl concur dt math fsmisc progpar reader rng sqlixx str testo ttpl cfg jrpc mulf net os url uuid fcgi http pgfe ws web"
algo_deps=""
assert_deps=""
base_deps=""
filesystem_deps=""
mem_deps=""
rajson_deps="thirdparty_rapidjson assert testo"
wscl_deps="assert testo thirdparty_uwsc"
concur_deps="assert testo"
dt_deps="assert testo"
math_deps="assert testo"
fsmisc_deps="filesystem"
progpar_deps="assert filesystem testo"
reader_deps="assert filesystem"
rng_deps="assert"
sqlixx_deps="assert filesystem"
str_deps="assert"
testo_deps="assert"
ttpl_deps="assert testo"
cfg_deps="assert filesystem reader str"
jrpc_deps="assert testo math thirdparty_rapidjson rajson str"
mulf_deps="assert str testo"
net_deps="assert base filesystem testo progpar os"
os_deps="assert filesystem testo progpar"
url_deps="assert str testo"
uuid_deps="assert rng testo"
fcgi_deps="assert filesystem testo math base progpar os net"
http_deps="assert testo dt base filesystem progpar os net str"
pgfe_deps="assert base filesystem mem testo progpar os net reader str"
ws_deps="assert filesystem base testo progpar os net thirdparty_usockets thirdparty_uwebsockets"
web_deps="assert filesystem testo math base progpar os net fcgi dt str http thirdparty_rapidjson rajson jrpc mulf reader ttpl"
