#!/bin/bash
# Copyright (C) Dmitry Igrishin

cefeika_libraries_with_tests="assert rajson wscl concur dt math progpar sqlixx str testo ttpl jrpc mulf net os url uuid fcgi http pgfe ws web"
assert_test_deps=""
rajson_test_deps="filesystem reader testo"
wscl_test_deps="testo"
concur_test_deps="testo"
dt_test_deps="testo"
math_test_deps="testo"
progpar_test_deps="testo"
sqlixx_test_deps="testo"
str_test_deps="testo"
testo_test_deps=""
ttpl_test_deps="testo"
jrpc_test_deps="math testo"
mulf_test_deps="filesystem reader testo"
net_test_deps="testo"
os_test_deps="testo"
url_test_deps="str testo"
uuid_test_deps="rng testo"
fcgi_test_deps="pthread rng testo"
http_test_deps="dt testo"
pgfe_test_deps="os reader testo"
ws_test_deps="rng testo"
web_test_deps=""
