#!/bin/bash
# Copyright (C) 2021 Dmitry Igrishin

# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.

# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:

# 1. The origin of this software must not be misrepresented; you must not
#    claim that you wrote the original software. If you use this software
#    in a product, an acknowledgment in the product documentation would be
#    appreciated but is not required.
# 2. Altered source versions must be plainly marked as such, and must not be
#    misrepresented as being the original software.
# 3. This notice may not be removed or altered from any source distribution.

script_dir=$(dirname "$0")
. "${script_dir}/cefeika_deps.sh" || exit $?

# For cp "$src/$lib"/*.!(test) "$dst/$lib"
shopt -s extglob

err()
{
  echo $* >&2
  exit 1
}

usage()
{
  err "usage: $0 [-T] library... path-to-destination-root"
}

while getopts T opt
do
  case $opt in
    T) without_tests=1 ;;
    ?) usage ;;
  esac
done
shift `expr $OPTIND - 1`

if [ $# -lt 2 ]; then
  usage
fi

src=$(realpath "${script_dir}/..")
while [ $# -gt 1 ]; do
  if [ ! -d "$src/$1" ]; then
    err "unknown library specified -- $1"
  fi
  libs="$libs $1"
  shift
done
dst=$1

# $1 - lib
copy_lib()
{
  local lib=$1
  local thirdparty_re='^thirdparty_+'
  if [[ $lib =~ $thirdparty_re ]]; then
    lib=$(echo "$lib" | sed -E 's/thirdparty_(.*)$/thirdparty\/\1/g')
    mkdir -p "$dst/thirdparty" || exit $?
  fi
  if [ -d "$src/$lib" ]; then
    mkdir -p "$dst/$lib" || exit $?
    cp "$src/$lib"/*.!(test) "$dst/$lib" || exit $?
    if [ X"$without_tests" = X ]; then
      if [ -d "$src/$lib/test" ]; then
        cp -R "$src/$lib/test" "$dst/$lib" || exit $?
      fi
    fi
  else
    err "no library found -- $lib"
  fi
}

# Create the destination
mkdir -p $dst || exit $?

# Copy special stuff
for f in .editorconfig .gitattributes .gitignore CMakeLists.txt LICENSE.txt README.md; do
  cp "$src/$f" "$dst" || exit $?
done

# Copy special .in stuff
for f in dll.hpp lib.cpp lib.hpp version.hpp version.rc Doxyfile; do
  cp "$src/${f}.in" "$dst" || exit $?
done

# Copy CMake stuff
mkdir -p "$dst/cmake" || exit $?
cp -R "$src"/cmake/*.!(dmitigr_cefeika_libraries.cmake) "$dst/cmake" || exit $?

# Copy libraries
for lib in $libs; do
  # Copy library and it's dependencies
  deps=${lib}_deps
  deps=${!deps}
  for dep in $deps; do
    copy_lib $dep
  done
  copy_lib $lib
done

# Copy this script
mkdir -p "$dst/tool" || exit $?
cp "$0" "$dst/tool" || exit $?
