# -*- cmake -*-
# Copyright (C) Dmitry Igrishin
# For conditions of distribution and use, see file LICENSE.txt

set(dmitigr_cefeika_libraries "algo;assert;cfg;concur;endianness;enum_bitmask;filesystem;fsmisc;math;mem;progpar;reader;rng;str;testo;ttpl;uuid;mulf;url;dt;os;rajson;jrpc;net;fcgi;http;pgfe;sqlixx;ws;wscl;web")

set(dmitigr_cefeika_algo_deps)
set(dmitigr_cefeika_assert_deps)
set(dmitigr_cefeika_cfg_deps assert filesystem reader str)
set(dmitigr_cefeika_concur_deps assert)
set(dmitigr_cefeika_dt_deps assert)
set(dmitigr_cefeika_endianness_deps)
set(dmitigr_cefeika_enum_bitmask_deps)
set(dmitigr_cefeika_fcgi_deps assert filesystem math net)
set(dmitigr_cefeika_filesystem_deps)
set(dmitigr_cefeika_fsmisc_deps filesystem)
set(dmitigr_cefeika_http_deps assert dt net str)
set(dmitigr_cefeika_jrpc_deps assert math rajson str)
set(dmitigr_cefeika_math_deps assert)
set(dmitigr_cefeika_mem_deps)
set(dmitigr_cefeika_mulf_deps assert str)
set(dmitigr_cefeika_net_deps assert endianness enum_bitmask filesystem os)
set(dmitigr_cefeika_os_deps assert filesystem progpar)
set(dmitigr_cefeika_pgfe_deps enum_bitmask filesystem mem net str)
set(dmitigr_cefeika_progpar_deps assert filesystem)
set(dmitigr_cefeika_rajson_deps thirdparty_rapidjson)
set(dmitigr_cefeika_reader_deps assert filesystem)
set(dmitigr_cefeika_rng_deps assert)
set(dmitigr_cefeika_sqlixx_deps assert filesystem)
set(dmitigr_cefeika_str_deps assert)
set(dmitigr_cefeika_testo_deps assert)
set(dmitigr_cefeika_ttpl_deps assert)
set(dmitigr_cefeika_url_deps assert str)
set(dmitigr_cefeika_uuid_deps assert rng)
set(dmitigr_cefeika_web_deps assert fcgi filesystem http jrpc mulf reader str ttpl)
set(dmitigr_cefeika_ws_deps assert filesystem net thirdparty_usockets thirdparty_uwebsockets)
set(dmitigr_cefeika_wscl_deps assert thirdparty_uwsc)
set(dmitigr_cefeika_thirdparty_uwebsockets_deps thirdparty_usockets)
